import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const robotoRegular = localFont({
  src: "./fonts/RobotoRegular.ttf",
  variable: "--font-roboto-regular",
});
const robotoBold = localFont({
  src: "./fonts/RobotoBold.ttf",
  variable: "--font-roboto-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoRegular.variable} ${robotoBold.variable}`}>
        {children}
      </body>
    </html>
  );
}
